### ISSUE TITLE
Spigot 1.8.5 OptimizedTileEntityBeacon crash.

### ISSUE THREAD

**Issue by Leymooo** [True-Games/TickOptimizer#2]
http://hastebin.com/xehulecuzo.avrasm

how fix it? It This occurs when a player enter to server.

**Comment by Shevchik** [comment]
Not compatible with 1.7.5 right now

**Comment by Leymooo** [comment]
1.7.5? Maybe 1.8.5?
А вообще скоро исправишь? Пришлось убрать сейчас этот плагин.

**Comment by Leymooo** [comment]
Исправь ещё TNTRun
