### ISSUE TITLE
[Discussion] Spigot + TickOptimizer vs PaperSpigot

### ISSUE THREAD

**Issue by swan201** [True-Games/TickOptimizer#3]
I'm very useful to using TickOptimizer Plugins. After recent commit update, bungeecord network moving speed is very improve to using this.

I Test this plugins to using with PaperSpigot but doesnt work at all. How do you think witch case have more good performence?

Spigot + TickOptimizer or PaperSpigot. (or If you develop PaperSpigot's TickOptimizer, PaperSpigot + TickOptimizer)

**Comment by Shevchik** [comment]
Spigot + TickOptimizer will be better. TickOptimizer has all the performance improvements PaperSpigot have (except from block chest ocelot present on open check) + Improved usercache, tweaks at networking level, beacon optimizations (do not load chunks of structure checks, do not calculate and track beam colors (why is it even done on serverside too?)).
