### ISSUE TITLE
Build Error?

### ISSUE THREAD

**Issue by swan201** [True-Games/TickOptimizer#4]
Eclipse Building Error say

Errors occurred during the build.
Errors running builder 'Java Builder' on project 'TickOptimizer'.
Unexpected RHS PolyTypeBinding for: new LinkedHashSetQueue<>()

**Comment by Shevchik** [comment]
Build using ANT, and don't forget to build using java8.

**Comment by swan201** [comment]
@Shevchik I think you need to change ant build.xml change default java source version target change 1.7 to 1.8 :), Thanks
