### ISSUE TITLE
PaperSpigot is TacoSpigot

### ISSUE THREAD

**Issue by FunnyCraft** [True-Games/TickOptimizer#8]
Твой плагин работает с PaperSpigot?
И еще где лучше производительность?

**Comment by Shevchik** [comment]
100% works with TacoSpigot. No guarantee with other server implementations.

TickOptimizer adds some optimizations on top of TacoSpigot.

**Comment by FunnyCraft** [comment]
По производительности лучше TacoSpigot или PaperSpigot?
