### ISSUE TITLE
Извини за надоедливость, но ты так и не ответил.

### ISSUE THREAD

**Issue by FunnyCraft** [True-Games/TickOptimizer#9]
По производительности лучше TacoSpigot или PaperSpigot?

**Comment by Shevchik** [comment]
TacoSpigot.

**Comment by FunnyCraft** [comment]
Если к TacoSpigot добавить еще TickOptimizator то будет лучше?

**Comment by Shevchik** [comment]
Да. Иначе бы этот плагин не существовал.

**Comment by FunnyCraft** [comment]
Еще последний вопрос PaperSpigot vs TacoSpigot.
В процентом соотношении, по производительности можешь примерно сказать.
